version: 2.1
setup: true # Required for dynamic config

orbs:
  path-filtering: circleci/path-filtering@3.0.0

workflows:
  dispatch:
    jobs:
      - path-filtering/filter:
          base-revision: main
          config-path: .circleci/continue-config.yml
          mapping: |
            .* run-data-backend true