version: 2.1
setup: true # Required for dynamic config

orbs:
  path-filtering: circleci/path-filtering@1.0.0

workflows:
  dispatch:
    jobs:
      - path-filtering/filter:
          base-revision: main
          config-path: .circleci/continue_config.yml
          mapping: |
            data-backend/.* run-data-backend true
            backend/.* run-backend true